# The URL the site will be built for
base_url = "https://tristramg.eu"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# theme = ""

taxonomies = [
    # You can enable/disable RSS
    { name = "categories", rss = true },
    { name = "tags", rss = true },
]

author = "Tristram Gräbener"
generate_feeds = true
default_language = "fr"

[extra]
# Put all your custom variables here

[markdown]
insert_anchor_links = "left"

[markdown.highlighting]
# When set to "true", missing highlight languages are treated as errors. Defaults to false but recommended to set to true.
error_on_missing_language = false
light_theme = "github-light"                                                                                     
dark_theme = "github-dark"
