# On every push this script is executed
on:
  push:
    branches:
      - main
name: Build and deploy GH Pages
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@v4
    # Build & deploy
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@v0.19.2
      env:
        # Provide personal access token
        TOKEN: ${{ secrets.TOKEN }}
